---
title: "Demo for Starbucks vs DD around NYC"
author: "Nikky Xiong"
date: "3/6/2020"
output:
  html_document: default
  pdf_document: default
---

# Data from Department of Health and Mental Hygiene (DOHMH) - New York City Restaurant Inspection Results, and the link is here: https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Clean up the Data

```{r, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(stringr)

df <- read.csv('raw_data/coffee_compare.csv')
coffee <- df %>% select(DBA, reinspections, checks, violations, 
                        score, inspections, BORO, SCORE)
coffee$DBA = ifelse(str_detect(coffee$DBA, "DUNKIN"), 'DD', 'Starbucks')
coffee %>% 
    select(BORO, DBA) %>% 
    group_by(BORO) %>% 
    table()
```

# Visualization

```{r, message=FALSE, warning=FALSE}
library(ggthemes)
library(ggplot2)
library(plotly)

coffee_new <- coffee %>% 
    group_by(DBA, BORO) %>% 
    summarize(Value = n())

pc <- ggplot(coffee_new, aes(fill=DBA, y=Value, x=BORO)) + 
    geom_bar(position="dodge", stat="identity", width = 0.5) +
    xlab('Neighborhood') + 
    ylab('Health Violations') + 
    labs(caption = 'Data Source: DOHMH',
         fill = 'Brands') +
    ggtitle('Health Violations of Coffee Brands by Neighborhoods') +
    theme_bw() +
    scale_fill_manual(values = c("#f09a56", "#87dc97")) +
    theme(plot.title = element_text(size=12, face="bold", hjust = 0.5),
          legend.text = element_text(size=8),
          legend.title = element_text(size=8))
pc
```

```{r}
pc1 <- ggplot(coffee, aes(x = BORO, y = violations, color = DBA)) + 
    geom_point(alpha = 0.5) +
    xlab('Neighborhood') + 
    ylab('Health Violations') + 
    labs(caption = 'DOHMH') +
    ggtitle('Health Violations of Coffee Brands by Neighborhoods') +
    theme_bw() +
    theme(plot.title = element_text(size=12, face="bold", hjust = 0.5),
          legend.text = element_text(size=8),
          legend.title = element_text(size=8)) +
    scale_color_manual(values = c("DD" = "#f09a56", 
                                  'Starbucks' = "#87dc97"))
ggplotly(pc1)
```

```{r}
coffee_new <- coffee %>% 
    group_by(DBA, BORO) %>% 
    summarize(total_vio = sum(violations, na.rm = T))

pc11 <- ggplot(coffee_new, 
               aes(fill=DBA, y=total_vio, x=BORO)) + 
    geom_bar(position="dodge", stat="identity", width = 0.5) +
    xlab('Neighborhood') + 
    ylab('Health Violations') + 
    labs(caption = 'Data Source: DOHMH',
         fill = 'Brands') +
    ggtitle('Health Violations of Coffee Brands by Neighborhoods') +
    theme_bw() +
    scale_fill_manual(values = c("#f09a56", "#87dc97")) +
    theme(plot.title = element_text(size=12, face="bold", hjust = 0.5),
          legend.text = element_text(size=8),
          legend.title = element_text(size=8))
pc11
```


```{r}
pc2 <- ggplot(coffee, aes(x = BORO, y = SCORE, color = DBA)) + 
    geom_point(alpha = 0.5) +
    xlab('Neighborhood') + 
    ylab('Total Score for a Particular Inspection') + 
    labs(caption = 'DOHMH') +
    ggtitle('Score of Coffee Brands by Neighborhoods') +
    theme_bw() +
    theme(plot.title = element_text(size=12, face="bold", hjust = 0.5),
          legend.text = element_text(size=8),
          legend.title = element_text(size=8)) +
    scale_color_manual(values = c("DD" = "#f09a56", 
                                  'Starbucks' = "#87dc97"))
ggplotly(pc2)
```

```{r}
coffee_new <- coffee %>% 
    group_by(DBA, BORO) %>% 
    summarize(total_score = sum(SCORE, na.rm = T))

pc11 <- ggplot(coffee_new, 
               aes(fill=DBA, y=total_score, x=BORO)) + 
    geom_bar(position="dodge", stat="identity", width = 0.5) +
    xlab('Neighborhood') + 
    ylab('Total Score for a Particular Inspection') + 
    labs(caption = 'Data Source: DOHMH',
         fill = 'Brands') +
    ggtitle('Inspection Score of Coffee Brands by Neighborhoods') +
    theme_bw() +
    scale_fill_manual(values = c("#f09a56", "#87dc97")) +
    theme(plot.title = element_text(size=12, face="bold", hjust = 0.5),
          legend.text = element_text(size=8),
          legend.title = element_text(size=8))
pc11
```

# Linear Regression Analysis 

```{r}
coffee_lm <- coffee %>% 
    group_by(DBA, BORO) %>% 
    summarize(total_num = n(),
              total_vio = sum(violations, na.rm = T),
              total_score = sum(SCORE, na.rm = T))
coffee_lm$DBA = ifelse(coffee_lm$DBA == "DD", 1, 0)

coffee_sb <- coffee_lm %>% filter(DBA == 1)
coffee_dd <- coffee_lm %>% filter(DBA == 0)
```

```{r}
lm <- lm(total_num ~ total_vio + total_score,
         data = coffee_sb)
summary(lm)
```

```{r}
lm <- lm(total_num ~ total_vio + total_score,
         data = coffee_dd)
summary(lm)
```

```{r}
lm1 <- lm(total_vio ~ total_num,
         data = coffee_sb)
summary(lm1)
```

```{r}
lm1 <- lm(total_vio ~ total_num,
         data = coffee_dd)
summary(lm1)
```

```{r}
lm2 <- lm(total_vio ~ total_num*DBA,
         data = coffee_lm)
summary(lm2)
```

```{r}
lm2 <- lm(total_score ~ total_num*DBA,
         data = coffee_lm)
summary(lm2)
```

# Supervised Machine Learning

### Question: Whether can be told the coffee store is Starbucks or not?
### Binary outcome in this case.

```{r, warning=FALSE, message=FALSE}
library(caret)

coffee$DBA = ifelse(coffee$DBA == "DD", 0, 1)
coffee$DBA <- factor(coffee$DBA, 
                     labels = c("Starbucks", "DD"), 
                     levels = 1:0) 
set.seed(12345)
in_train <- createDataPartition(y = coffee$DBA, 
                                p = 0.8, list = FALSE)
training <- coffee[ in_train, ]
testing  <- coffee[-in_train, ]
```

```{r}
logit <- glm(DBA ~ checks + violations + score + BORO, 
             data = training, family = binomial(link = "logit"))

y_hat_logit <- predict(logit, newdata = testing, type = "response")
z_logit <- factor(y_hat_logit > 0.5, 
                  levels = c(TRUE, FALSE), 
                  labels = c("Starbucks", "DD"))

confusionMatrix(z_logit, reference = testing$DBA)
```

```{r}
LDA <- train(DBA ~ checks + violations + score + BORO, 
             data = training, method = "lda", 
             reProcess = c("center", "scale"))
z <- predict(LDA, newdata = testing)
confusionMatrix(z, testing$DBA)
```

