---
title: "BB API Request"
author: "Nikky Xiong"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
devtools::install_github("OmaymaS/yelpr")
library(yelpr)
library(jsonlite)
library(dplyr)
library(tidyverse)
key <- Sys.getenv("YELP_KEY")
```

# All NYC
```{r}
nyc_restaurants <- business_search(api_key = key,
                location = 'New York City',
                term = "Blue Bottle",
                limit = 50)

varnames <- c("id", "alias", "name", "image_url", "is_closed", "url", "review_count", "rating", "latitude", "longitude", "transactions", "price", "distance", "street_address", "city", "state", "zip_code")
restaurants_df <- data.frame(cbind(as.character(nyc_restaurants$businesses$id), 
                        as.character(nyc_restaurants$businesses$alias), 
                        as.character(nyc_restaurants$businesses$name),
                        as.character(nyc_restaurants$businesses$image_url), 
                        as.logical(nyc_restaurants$businesses$is_closed),
                        as.character(nyc_restaurants$businesses$url),
                        as.numeric(nyc_restaurants$businesses$review_count),
                        as.numeric(nyc_restaurants$businesses$rating),
                        as.numeric(nyc_restaurants$businesses$coordinates$latitude),
                        as.numeric(nyc_restaurants$businesses$coordinates$longitude),
                        as.character(nyc_restaurants$businesses$transactions), 
                        as.character(nyc_restaurants$businesses$price),
                        as.numeric(nyc_restaurants$businesses$distance),
                        as.character(nyc_restaurants$businesses$location$address1),
                        as.character(nyc_restaurants$businesses$location$city),
                        as.character(nyc_restaurants$businesses$location$state),
                        as.numeric(nyc_restaurants$businesses$location$zip_code)), stringsAsFactors = FALSE)

colnames(restaurants_df) <- varnames

# rest_cats <- data.frame(unlist(nyc_restaurants$businesses$categories[[1]]))

#restaurants_df$categories <- nyc_restaurants$businesses$categories[[1]]

for (i in 1:ncol(restaurants_df)) {
  restaurants_df$categories[i] <- paste0(flatten(nyc_restaurants$businesses$categories[[i]]), sep = ", ", collapse = "")
  restaurants_df$full_address[i] <- paste0(flatten(nyc_restaurants$businesses$location$display_address[i]), sep = ", ", collapse = "")
}

write_csv(restaurants_df, "./nyc_BB.csv", na = "NA")
```

# Manhattan Restaurants
```{r}
nyc_restaurants <- business_search(api_key = key,
                location = 'Manhattan',
                term = "Blue Bottle",
                limit = 50)

varnames <- c("id", "alias", "name", "image_url", "is_closed", "url", "review_count", "rating", "latitude", "longitude", "transactions", "price", "distance", "street_address", "city", "state", "zip_code")
restaurants_df <- data.frame(cbind(as.character(nyc_restaurants$businesses$id), 
                        as.character(nyc_restaurants$businesses$alias), 
                        as.character(nyc_restaurants$businesses$name),
                        as.character(nyc_restaurants$businesses$image_url), 
                        as.logical(nyc_restaurants$businesses$is_closed),
                        as.character(nyc_restaurants$businesses$url),
                        as.numeric(nyc_restaurants$businesses$review_count),
                        as.numeric(nyc_restaurants$businesses$rating),
                        as.numeric(nyc_restaurants$businesses$coordinates$latitude),
                        as.numeric(nyc_restaurants$businesses$coordinates$longitude),
                        as.character(nyc_restaurants$businesses$transactions), 
                        as.character(nyc_restaurants$businesses$price),
                        as.numeric(nyc_restaurants$businesses$distance),
                        as.character(nyc_restaurants$businesses$location$address1),
                        as.character(nyc_restaurants$businesses$location$city),
                        as.character(nyc_restaurants$businesses$location$state),
                        as.numeric(nyc_restaurants$businesses$location$zip_code)), stringsAsFactors = FALSE)

colnames(restaurants_df) <- varnames

# rest_cats <- data.frame(unlist(nyc_restaurants$businesses$categories[[1]]))

#restaurants_df$categories <- nyc_restaurants$businesses$categories[[1]]

for (i in 1:ncol(restaurants_df)) {
  restaurants_df$categories[i] <- paste0(flatten(nyc_restaurants$businesses$categories[[i]]), sep = ", ", collapse = "")
  restaurants_df$full_address[i] <- paste0(flatten(nyc_restaurants$businesses$location$display_address[i]), sep = ", ", collapse = "")
}

restaurants_df_backup <- restaurants_df
write_csv(restaurants_df, "./manhattan_BB.csv", na = "NA")
```

# Brooklyn
```{r}
nyc_restaurants <- business_search(api_key = key,
                location = 'Brooklyn',
                term = "Blue Bottle",
                limit = 50)

varnames <- c("id", "alias", "name", "image_url", "is_closed", "url", "review_count", "rating", "latitude", "longitude", "transactions", "price", "distance", "street_address", "city", "state", "zip_code")
restaurants_df <- data.frame(cbind(as.character(nyc_restaurants$businesses$id), 
                        as.character(nyc_restaurants$businesses$alias), 
                        as.character(nyc_restaurants$businesses$name),
                        as.character(nyc_restaurants$businesses$image_url), 
                        as.logical(nyc_restaurants$businesses$is_closed),
                        as.character(nyc_restaurants$businesses$url),
                        as.numeric(nyc_restaurants$businesses$review_count),
                        as.numeric(nyc_restaurants$businesses$rating),
                        as.numeric(nyc_restaurants$businesses$coordinates$latitude),
                        as.numeric(nyc_restaurants$businesses$coordinates$longitude),
                        as.character(nyc_restaurants$businesses$transactions), 
                        as.character(nyc_restaurants$businesses$price),
                        as.numeric(nyc_restaurants$businesses$distance),
                        as.character(nyc_restaurants$businesses$location$address1),
                        as.character(nyc_restaurants$businesses$location$city),
                        as.character(nyc_restaurants$businesses$location$state),
                        as.numeric(nyc_restaurants$businesses$location$zip_code)), stringsAsFactors = FALSE)

colnames(restaurants_df) <- varnames

# rest_cats <- data.frame(unlist(nyc_restaurants$businesses$categories[[1]]))

#restaurants_df$categories <- nyc_restaurants$businesses$categories[[1]]

for (i in 1:ncol(restaurants_df)) {
  restaurants_df$categories[i] <- paste0(flatten(nyc_restaurants$businesses$categories[[i]]), sep = ", ", collapse = "")
  restaurants_df$full_address[i] <- paste0(flatten(nyc_restaurants$businesses$location$display_address[i]), sep = ", ", collapse = "")
}

write_csv(restaurants_df, "./Brooklyn_BB.csv", na = "NA")
```

# Queens
```{r}
nyc_restaurants <- business_search(api_key = key,
                location = 'Queens',
                term = "Blue Bottle",
                limit = 50)

varnames <- c("id", "alias", "name", "image_url", "is_closed", "url", "review_count", "rating", "latitude", "longitude", "transactions", "price", "distance", "street_address", "city", "state", "zip_code")
restaurants_df <- data.frame(cbind(as.character(nyc_restaurants$businesses$id), 
                        as.character(nyc_restaurants$businesses$alias), 
                        as.character(nyc_restaurants$businesses$name),
                        as.character(nyc_restaurants$businesses$image_url), 
                        as.logical(nyc_restaurants$businesses$is_closed),
                        as.character(nyc_restaurants$businesses$url),
                        as.numeric(nyc_restaurants$businesses$review_count),
                        as.numeric(nyc_restaurants$businesses$rating),
                        as.numeric(nyc_restaurants$businesses$coordinates$latitude),
                        as.numeric(nyc_restaurants$businesses$coordinates$longitude),
                        as.character(nyc_restaurants$businesses$transactions), 
                        as.character(nyc_restaurants$businesses$price),
                        as.numeric(nyc_restaurants$businesses$distance),
                        as.character(nyc_restaurants$businesses$location$address1),
                        as.character(nyc_restaurants$businesses$location$city),
                        as.character(nyc_restaurants$businesses$location$state),
                        as.numeric(nyc_restaurants$businesses$location$zip_code)), stringsAsFactors = FALSE)

colnames(restaurants_df) <- varnames

# rest_cats <- data.frame(unlist(nyc_restaurants$businesses$categories[[1]]))

#restaurants_df$categories <- nyc_restaurants$businesses$categories[[1]]

for (i in 1:ncol(restaurants_df)) {
  restaurants_df$categories[i] <- paste0(flatten(nyc_restaurants$businesses$categories[[i]]), sep = ", ", collapse = "")
  restaurants_df$full_address[i] <- paste0(flatten(nyc_restaurants$businesses$location$display_address[i]), sep = ", ", collapse = "")
}


write_csv(restaurants_df, "./Queens_BB.csv", na = "NA")
```


# Bronx
```{r}
nyc_restaurants <- business_search(api_key = key,
                location = 'Bronx',
                term = "Blue Bottle",
                limit = 50)

varnames <- c("id", "alias", "name", "image_url", "is_closed", "url", "review_count", "rating", "latitude", "longitude", "transactions", "price", "distance", "street_address", "city", "state", "zip_code")
restaurants_df <- data.frame(cbind(as.character(nyc_restaurants$businesses$id), 
                        as.character(nyc_restaurants$businesses$alias), 
                        as.character(nyc_restaurants$businesses$name),
                        as.character(nyc_restaurants$businesses$image_url), 
                        as.logical(nyc_restaurants$businesses$is_closed),
                        as.character(nyc_restaurants$businesses$url),
                        as.numeric(nyc_restaurants$businesses$review_count),
                        as.numeric(nyc_restaurants$businesses$rating),
                        as.numeric(nyc_restaurants$businesses$coordinates$latitude),
                        as.numeric(nyc_restaurants$businesses$coordinates$longitude),
                        as.character(nyc_restaurants$businesses$transactions), 
                        as.character(nyc_restaurants$businesses$price),
                        as.numeric(nyc_restaurants$businesses$distance),
                        as.character(nyc_restaurants$businesses$location$address1),
                        as.character(nyc_restaurants$businesses$location$city),
                        as.character(nyc_restaurants$businesses$location$state),
                        as.numeric(nyc_restaurants$businesses$location$zip_code)), stringsAsFactors = FALSE)

colnames(restaurants_df) <- varnames

# rest_cats <- data.frame(unlist(nyc_restaurants$businesses$categories[[1]]))

#restaurants_df$categories <- nyc_restaurants$businesses$categories[[1]]

for (i in 1:ncol(restaurants_df)) {
  restaurants_df$categories[i] <- paste0(flatten(nyc_restaurants$businesses$categories[[i]]), sep = ", ", collapse = "")
  restaurants_df$full_address[i] <- paste0(flatten(nyc_restaurants$businesses$location$display_address[i]), sep = ", ", collapse = "")
}



restaurants_df_backup <- restaurants_df
write_csv(restaurants_df, "./Bronx_BB.csv", na = "NA")
```


# Staten Island
```{r}
nyc_restaurants <- business_search(api_key = key,
                location = 'Staten Island',
                term = "Blue Bottle",
                limit = 50)

varnames <- c("id", "alias", "name", "image_url", "is_closed", "url", "review_count", "rating", "latitude", "longitude", "transactions", "price", "distance", "street_address", "city", "state", "zip_code")
restaurants_df <- data.frame(cbind(as.character(nyc_restaurants$businesses$id), 
                        as.character(nyc_restaurants$businesses$alias), 
                        as.character(nyc_restaurants$businesses$name),
                        as.character(nyc_restaurants$businesses$image_url), 
                        as.logical(nyc_restaurants$businesses$is_closed),
                        as.character(nyc_restaurants$businesses$url),
                        as.numeric(nyc_restaurants$businesses$review_count),
                        as.numeric(nyc_restaurants$businesses$rating),
                        as.numeric(nyc_restaurants$businesses$coordinates$latitude),
                        as.numeric(nyc_restaurants$businesses$coordinates$longitude),
                        as.character(nyc_restaurants$businesses$transactions), 
                        as.character(nyc_restaurants$businesses$price),
                        as.numeric(nyc_restaurants$businesses$distance),
                        as.character(nyc_restaurants$businesses$location$address1),
                        as.character(nyc_restaurants$businesses$location$city),
                        as.character(nyc_restaurants$businesses$location$state),
                        as.numeric(nyc_restaurants$businesses$location$zip_code)), stringsAsFactors = FALSE)

colnames(restaurants_df) <- varnames

# rest_cats <- data.frame(unlist(nyc_restaurants$businesses$categories[[1]]))

#restaurants_df$categories <- nyc_restaurants$businesses$categories[[1]]

for (i in 1:ncol(restaurants_df)) {
  restaurants_df$categories[i] <- paste0(flatten(nyc_restaurants$businesses$categories[[i]]), sep = ", ", collapse = "")
  restaurants_df$full_address[i] <- paste0(flatten(nyc_restaurants$businesses$location$display_address[i]), sep = ", ", collapse = "")
}

write_csv(restaurants_df, "./StatenIsland_BB.csv", na = "NA")
```

